export const MOLDOVA_REGIONS = [
  "Кишинёв",
  "Бельцы",
  "Бендеры",
  "Гагаузия (АТО)",
  "Новоаненский район (Anenii Noi)",
  "Бессарабский район (Basarabeasca)",
  "Бричанский район (Briceni)",
  "Кагульский район (Cahul)",
  "Кантемирский район (Cantemir)",
  "Каушанский район (Căușeni)",
  "Чимишлийский район (Cimișlia)",
  "Криулянский район (Criuleni)",
  "Дондюшанский район (Dondușeni)",
  "Дрокиевский район (Drochia)",
  "Дубоссарский район (Dubăsari)",
  "Единецкий район (Edineț)",
  "Фалештский район (Fălești)",
  "Флорештский район (Florești)",
  "Глодянский район (Glodeni)",
  "Хынчештский район (Hîncești)",
  "Яловенский район (Ialoveni)",
  "Леовский район (Leova)",
  "Ниспоренский район (Nisporeni)",
  "Окницкий район (Ocnița)",
  "Оргеевский район (Orhei)",
  "Резинский район (Rezina)",
  "Рышканский район (Rîșcani)",
  "Сынжерейский район (Sîngerei)",
  "Сорокский район (Soroca)",
  "Страшенский район (Strășeni)",
  "Шолданештский район (Șoldănești)",
  "Штефан-Водский район (Ștefan Vodă)",
  "Тараклийский район (Taraclia)",
  "Теленештский район (Telenești)",
  "Унгенский район (Ungheni)",
  "Приднестровье",
] as const;

export type MoldovaRegion = (typeof MOLDOVA_REGIONS)[number];

export const MOLDOVA_REGION_LABELS_RO: Record<MoldovaRegion, string> = {
  Кишинёв: "Chișinău",
  Бельцы: "Bălți",
  Бендеры: "Bender (Tighina)",
  "Гагаузия (АТО)": "UTA Găgăuzia",
  "Новоаненский район (Anenii Noi)": "Raionul Anenii Noi",
  "Бессарабский район (Basarabeasca)": "Raionul Basarabeasca",
  "Бричанский район (Briceni)": "Raionul Briceni",
  "Кагульский район (Cahul)": "Raionul Cahul",
  "Кантемирский район (Cantemir)": "Raionul Cantemir",
  "Каушанский район (Căușeni)": "Raionul Căușeni",
  "Чимишлийский район (Cimișlia)": "Raionul Cimișlia",
  "Криулянский район (Criuleni)": "Raionul Criuleni",
  "Дондюшанский район (Dondușeni)": "Raionul Dondușeni",
  "Дрокиевский район (Drochia)": "Raionul Drochia",
  "Дубоссарский район (Dubăsari)": "Raionul Dubăsari",
  "Единецкий район (Edineț)": "Raionul Edineț",
  "Фалештский район (Fălești)": "Raionul Fălești",
  "Флорештский район (Florești)": "Raionul Florești",
  "Глодянский район (Glodeni)": "Raionul Glodeni",
  "Хынчештский район (Hîncești)": "Raionul Hîncești",
  "Яловенский район (Ialoveni)": "Raionul Ialoveni",
  "Леовский район (Leova)": "Raionul Leova",
  "Ниспоренский район (Nisporeni)": "Raionul Nisporeni",
  "Окницкий район (Ocnița)": "Raionul Ocnița",
  "Оргеевский район (Orhei)": "Raionul Orhei",
  "Резинский район (Rezina)": "Raionul Rezina",
  "Рышканский район (Rîșcani)": "Raionul Rîșcani",
  "Сынжерейский район (Sîngerei)": "Raionul Sîngerei",
  "Сорокский район (Soroca)": "Raionul Soroca",
  "Страшенский район (Strășeni)": "Raionul Strășeni",
  "Шолданештский район (Șoldănești)": "Raionul Șoldănești",
  "Штефан-Водский район (Ștefan Vodă)": "Raionul Ștefan Vodă",
  "Тараклийский район (Taraclia)": "Raionul Taraclia",
  "Теленештский район (Telenești)": "Raionul Telenești",
  "Унгенский район (Ungheni)": "Raionul Ungheni",
  Приднестровье: "Regiunea transnistreană",
};
